### ISSUE TITLE
安卓7.1.1使用后无法登录需要认证的wifi

### ISSUE THREAD

**Issue by KyonCN** [Noisyfox/NoExclamation#1]
叹号消失了，但是无法跳转到wifi认证界面

**Comment by Noisyfox** [comment]
你用的是哪个网址？

**Comment by KyonCN** [comment]
@Noisyfox 软件自带的noisfox 显示隐私错误

**Comment by Noisyfox** [comment]
估计是https的锅。。。因为你试图访问的是noisyfox.cn但是确被跳转到了wifi认证界。
这个问题待我有空研究一下。如果可以的话你试试看先把https认证关了，改成http，应该可以

**Comment by Noisyfox** [comment]
Close due to inactive.
