### ISSUE TITLE
Android 7.1.2 无法禁用检测

### ISSUE THREAD

**Issue by jingyu9575** [Noisyfox/NoExclamation#2]
“Captive Portal检测”设为Off在Android 7.1.2中无效。

设置项captive_portal_detection_enabled在最新源码中已废弃，改为captive_portal_mode：0-禁用，1-启用，2-检测到需要登录时断开连接并忘记网络。[Google Source](https://android.googlesource.com/platform/frameworks/base/+/android-7.1.2_r17/core/java/android/provider/Settings.java), [LineageOS](https://github.com/LineageOS/android_frameworks_base/blob/cm-14.1/core/java/android/provider/Settings.java)

**Comment by Noisyfox** [comment]
哇。。。。这API改的这么频繁。。。真的气。。。

**Comment by Noisyfox** [comment]
@jingyu9575 哇这个好像还不太好改。。。7.1.2和7.1.1不好区分，而且还没有7.1.2的模拟器可以测试。。。你现在是在pixel上用上的7.1.2么？

**Comment by jingyu9575** [comment]
华为荣耀8，在xda上找的ROM，Resurrection Remix Nougat 7.1.2_r8。

是否可以用反射检查上面源代码中的常量？
```
boolean isNewApi = true;
try {
    android.provider.Settings.Global.class.getField("CAPTIVE_PORTAL_MODE");
} catch (NoSuchFieldException e) {
    isNewApi = false;
}
```
在这个系统上是true。

**Comment by Noisyfox** [comment]
嗯我更新了一下，在new_arch分支下，但是手头没有合适的机器可以测试。不知道你有没有条件自己编译一下试试看。

**Comment by jingyu9575** [comment]
7.1.2_r8测试可用。
![screenshot_20170701-171330](https://user-images.githubusercontent.com/8923139/27760734-8a9193dc-5e81-11e7-868a-cbb4bbbc12b5.png)  ![screenshot_20170701-171232](https://user-images.githubusercontent.com/8923139/27760737-8ef2a54c-5e81-11e7-8e60-0615365dacf1.png)  ![screenshot_20170701-172140](https://user-images.githubusercontent.com/8923139/27760786-40a61ba2-5e82-11e7-8ad0-e317520a6134.png)

**Comment by Noisyfox** [comment]
其它功能是不是正常的？
主要是这次我完全重写了整个逻辑，能不能帮我试一下每一种功能是不是能正确设置，以及当前值能不能正常刷新。

**Comment by jingyu9575** [comment]
所有功能都能正确查看、设置对应的settings。一键设置、刷新正常工作，修改任何一个设置都会刷新。
设为noisyfox.io可以去掉警告![warning](https://user-images.githubusercontent.com/8923139/27764534-7e3ccf8c-5ece-11e7-9b3f-63b387a4947a.png)。在我这里默认服务器不启动https也不会有警告，可能是校园网没墙这个http服务器。

服务地址的输入框有注入漏洞 ;-)
```
http://1.2.3.4/; my-evil-command-that-runs-as-root
```

**Comment by Noisyfox** [comment]
谢啦~
这个漏洞233333貌似没有什么特别方便的方法去改啊23333
不过因为这个只能手动输入，不会存在什么远程执行啥的，应该问题不大？

**Comment by Noisyfox** [comment]
话说我之前想到一个点子，就是专门弄一个子域名，比方说 g204.noisyfox.io , 然后对这个域名的任何路径访问都是返回204，感觉就不用担心谷歌又改网址格式了。

**Comment by Masterfans** [comment]
7.1.1好像就改成 private static final String DEFAULT_HTTPS_URL     = "https://www.google.com/generate_204";这个了，7.0.0还是DEFAULT_SERVER = "connectivitycheck.gstatic.com";
